name: Sync ECR image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: "Tag of the image in ECR (GIT SHA)"
        required: true
        default: "neuron-prd-latest"
      target_tag:
        description: "Tag to push to Docker Hub"
        required: true
        default: "latest"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        with: 
          registries: ${{ vars.AWS_ACCOUNT_INFRA_ID}}

      - name: Docker login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image from ECR
        run: |
          IMAGE_URI=${{ vars.AWS_ECR_PREFIX }}/infinite-games:${{ github.event.inputs.source_tag }}
          docker pull $IMAGE_URI

      - name: Retag image
        run: |
          IMAGE_URI=${{ vars.AWS_ECR_PREFIX }}/infinite-games:${{ github.event.inputs.source_tag }}
          TARGET=numinouslabs/numinous:${{ github.event.inputs.target_tag }}
          docker tag $IMAGE_URI $TARGET

      - name: Push image to Docker Hub
        run: |
          TARGET=numinouslabs/numinous:${{ github.event.inputs.target_tag }}
          docker push $TARGET
